# Generated by Django 4.0.2 on 2022-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
